### ISSUE TITLE
Error during installation pytgvoip

### ISSUE THREAD

**Issue by sumanake** [joel122002/telegram-outgoing-call-with-audio#1]
Hi, I cant install pytgvoip, i am using python 3.8 and installed according to your instructions.

Please help me, thank you very much.

```
(tele38) root@server-ubuntu:~# pip install pytgvoip
Collecting pytgvoip
  Using cached pytgvoip-0.0.7.1.tar.gz (2.1 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pytgvoip
  Building wheel for pytgvoip (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [106 lines of output]
      /root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/_distutils/dist.py:262: UserWarning: Unknown distribution option: 'python_required'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/tgvoip
      copying src/tgvoip/tgvoip.py -> build/lib.linux-x86_64-cpython-38/tgvoip
      copying src/tgvoip/utils.py -> build/lib.linux-x86_64-cpython-38/tgvoip
      copying src/tgvoip/__init__.py -> build/lib.linux-x86_64-cpython-38/tgvoip
      running build_ext
      -- The C compiler identification is GNU 7.5.0
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found PythonInterp: /root/miniconda3/envs/tele38/bin/python (found version "3.8.13")
      -- Found PythonLibs: /root/miniconda3/envs/tele38/lib/libpython3.8.so
      -- pybind11 v2.4.dev4
      -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1")
      -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
      -- Checking for module 'opus'
      --   Found opus, version 1.1.2
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- LTO enabled
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-install-75jcf5m9/pytgvoip_b585ee1dbc1a4e08b9345294f3d89923/build/temp.linux-x86_64-cpython-38
      [  0%] Building CXX object CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/Buffers.cpp.o
      [  0%] Building CXX object CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/EchoCanceller.cpp.o
      [  0%] Building CXX object CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/BlockingQueue.cpp.o
      [  1%] Building CXX object CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/CongestionControl.cpp.o
      [  1%] Building CXX object CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/JitterBuffer.cpp.o
      cc1plus: error: -Werror=class-memaccess: no option -Wclass-memaccess
      cc1plus: error: -Werror=class-memaccess: no option -Wclass-memaccess
      cc1plus: error: -Werror=class-memaccess: no option -Wclass-memaccess
      cc1plus: error: -Werror=class-memaccess: no option -Wclass-memaccess
      CMakeFiles/lib_tgvoip.dir/build.make:75: recipe for target 'CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/BlockingQueue.cpp.o' failed
      make[3]: *** [CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/BlockingQueue.cpp.o] Error 1
      make[3]: *** Waiting for unfinished jobs....
      CMakeFiles/lib_tgvoip.dir/build.make:117: recipe for target 'CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/EchoCanceller.cpp.o' failed
      make[3]: *** [CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/EchoCanceller.cpp.o] Error 1
      CMakeFiles/lib_tgvoip.dir/build.make:103: recipe for target 'CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/CongestionControl.cpp.o' failed
      make[3]: *** [CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/CongestionControl.cpp.o] Error 1
      CMakeFiles/lib_tgvoip.dir/build.make:89: recipe for target 'CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/Buffers.cpp.o' failed
      make[3]: *** [CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/Buffers.cpp.o] Error 1
      cc1plus: error: -Werror=class-memaccess: no option -Wclass-memaccess
      CMakeFiles/lib_tgvoip.dir/build.make:131: recipe for target 'CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/JitterBuffer.cpp.o' failed
      make[3]: *** [CMakeFiles/lib_tgvoip.dir/3rdparty/libtgvoip/JitterBuffer.cpp.o] Error 1
      CMakeFiles/Makefile2:137: recipe for target 'CMakeFiles/lib_tgvoip.dir/all' failed
      make[2]: *** [CMakeFiles/lib_tgvoip.dir/all] Error 2
      CMakeFiles/Makefile2:170: recipe for target 'CMakeFiles/_tgvoip.dir/rule' failed
      make[1]: *** [CMakeFiles/_tgvoip.dir/rule] Error 2
      Makefile:137: recipe for target '_tgvoip' failed
      make: *** [_tgvoip] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-75jcf5m9/pytgvoip_b585ee1dbc1a4e08b9345294f3d89923/setup.py", line 109, in <module>
          setup(
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/command/build.py", line 24, in run
          super().run()
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/root/miniconda3/envs/tele38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-75jcf5m9/pytgvoip_b585ee1dbc1a4e08b9345294f3d89923/setup.py", line 64, in run
          self.build_extension(ext)
        File "/tmp/pip-install-75jcf5m9/pytgvoip_b585ee1dbc1a4e08b9345294f3d89923/setup.py", line 91, in build_extension
          subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
        File "/root/miniconda3/envs/tele38/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--target', '_tgvoip', '--', '-j5']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by joel122002** [comment]
Are you sure you followed all the commands in readme?

**Comment by sumanake** [comment]
> Are you sure you followed all the commands in readme?

I found out I use cmake 7.5 which package requires cmake 8.
I tried it successfully, thank you very much

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-8 g++-8
gcc-8 --version

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8 
```
